/**
 * entries/*.md → src/entries.generated.ts (bundled, no fs at runtime) + INDEX.md.
 * Run after editing an entry: `pnpm --filter @qubo-portal/kb build`. The test
 * suite fails when either output is stale.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseEntry, type RawEntry } from "../src/parse";

const root = resolve(import.meta.dir, "..");

export function loadEntries(): RawEntry[] {
  const dir = resolve(root, "entries");
  const entries = readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => parseEntry(`entries/${f}`, readFileSync(resolve(dir, f), "utf8")));
  const seen = new Set<string>();
  for (const e of entries) {
    if (seen.has(e.id)) throw new Error(`duplicate id ${e.id}`);
    if (`entries/${e.id}.md` !== e.file) throw new Error(`${e.file}: file name must be <id>.md`);
    seen.add(e.id);
  }
  return entries;
}

export function generated(entries: RawEntry[]) {
  const ts = `// Generated by scripts/build.ts from entries/*.md. Do not edit.\nimport type { RawEntry } from "./parse";\n\nexport const ENTRIES: RawEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
  const rows = entries.map((e) => `| [${e.id}](entries/${e.id}.md) | ${e.title} | ${e.audience} | ${e.kind}${e.legal ? " · legal" : ""} | ${e.updated} |`);
  const index = [
    "# Knowledgebase index",
    "",
    "Generated by `pnpm --filter @qubo-portal/kb build`. Do not edit; edit `entries/*.md`.",
    "Numbers in entries are `{{placeholders}}` resolved from `@qubo-portal/plans` and `@qubo/protocol`.",
    "",
    "| Entry | Title | Audience | Kind | Updated |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
  return { ts, index };
}

if (import.meta.main) {
  const { ts, index } = generated(loadEntries());
  writeFileSync(resolve(root, "src/entries.generated.ts"), ts);
  writeFileSync(resolve(root, "INDEX.md"), index);
  console.log(`[kb] ${index.split("\n").filter((l) => l.startsWith("| [")).length} entries`);
}
